spring:
  application:
    name: auth-server
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0
  datasource:
      url: jdbc:mysql://localhost:3306/xz?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: yangzhixuan
      driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8001

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://admin:admin@localhost:9000/eureka/

##开启日志DEBUG级别，便于查看调试信息
logging:
  level:
    cn.poile: debug
    org.springframework.security: debug  # 关键：开启 Spring Security 调试日志
    org.springframework.web: debug
encrypt:
  key-store:
    location: classpath:/xz.keystore
    secret: xiaozuokeystore
    alias: xzkey
    password: xiaozuo