spring:
  application:
    name: auth-server
  datasource:
      url: jdbc:mysql://localhost:3306/xz?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: yangzhixuan
      driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8001

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://admin:admin@localhost:9000/eureka/

##开启日志DEBUG级别，便于查看调试信息
logging:
  level:
    cn.poile: debug
    org.springframework.security: debug  # 关键：开启 Spring Security 调试日志
    org.springframework.web: debug
encrypt:
  key-store:
    location: classpath:/xz.keystore
    secret: xiaozuokeystore
    alias: xzkey
    password: xiaozuo
auth:
  tokenValiditySecondsMobile: 31536000 #token存储到redis的过期时间
  tokenValiditySecondsComputer: 172800
  clientId: yaohw
  clientSecret: yaohw
  smsCodeTime: 10 #验证码有效时间，粒度为分钟