spring:
  application:
    name: cart-server

server:
  port: 8084

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://admin:admin@localhost:9000/eureka/

##开启日志DEBUG级别，便于查看调试信息
logging:
  level:
    cn.poile: info
    org.springframework: info
encrypt:
  key-store:
    location: classpath:/xz.keystore
    secret: xiaozuokeystore
    alias: xzkey
    password: xiaozuo